services:
  - type: web
    name: vite-express-app
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000